name: Bug Report
description: File a bug report
body:

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What you expected to see.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Observed/Actual behavior
      description: What you actually saw.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue.
    validations:
      required: true

  - type: checkboxes
    id: agreements
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I am running the latest version of the plugin.
          required: true
        - label: I have searched for and ensured there isn't already an open issue regarding this.
          required: true
        - label: I ticked all the boxes without actually reading them.
          required: false
        - label: My server software & version is supported by this plugin.
          required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, such as screenshots, logs or other relevant information.