blank_issues_enabled: false
contact_links:
  - name: Exploit Report
    url: https://discord.gg/8YRdnf5V42
    about: Since GitHub does not allow private issues, exploit reports are currently handled through our Discord.

  - name: Feature Request
    url: https://github.com/SytexMC/Plugin/discussions/new?category=feature-requests
    about: Share ideas and discuss potential new features.

  - name: Discord Server
    url: https://discord.gg/8YRdnf5V42
    about: If you have questions or need help, come join our Discord server!
